language: node_js
node_js:
- 7.1.0
env:
- CXX=g++-5.4.0
before_script:
- npm install -g istanbul
- npm install coveralls
after_success:
- istanbul cover --report lcovonly ./node_modules/tape/bin/tape './test/*-test.js' && cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-5.4.0
